server:
  port: 8082
  forward-headers-strategy: framework
jwt:
    secret: ${JWT_SECRET}
spring:
  application:
    name: BOOK-SERVICE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 172.26.234.58:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      #defaultZone: 'http://eureka-server:8761/eureka'
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  resilience4j:
    circuitbreaker:
      instances:
        authorService:
          register-health-indicator: true
          sliding-window-size: 10
          minimum-number-of-calls: 5
          permitted-number-of-calls-in-half-open-state: 3
          automatic-transition-from-open-to-half-open-enabled: true
          wait-duration-in-open-state: 10s
          failure-rate-threshold: 50
          event-consumer-buffer-size: 10
          record-exceptions:
            - feign.FeignException
            - java.io.IOException

        ratingService:
          register-health-indicator: true
          sliding-window-size: 10
          minimum-number-of-calls: 5
          permitted-number-of-calls-in-half-open-state: 3
          automatic-transition-from-open-to-half-open-enabled: true
          wait-duration-in-open-state: 10s
          failure-rate-threshold: 50
          event-consumer-buffer-size: 10
          record-exceptions:
            - feign.FeignException
            - java.io.IOException

    retry:
      instances:
        authorService:
          max-attempts: 3
          wait-duration: 1s
          retry-exceptions:
            - feign.FeignException
            - java.io.IOException

        ratingService:
          max-attempts: 3
          wait-duration: 1s
          retry-exceptions:
            - feign.FeignException
            - java.io.IOException